### ISSUE TITLE
pyperclip.PyperclipWindowsException: Error calling OpenClipboard ([WinError 5] Access is denied.)

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyperclip#119]
I'm trying to run a project (chess-alpha-zero) which uses your pyperclip package
I'm using anaconda python 3.6.4 64 bit on windows 10 with pyperclip 1.6.0 package from conda-forge

I am getting the following error:
Traceback (most recent call last):
  File "src/chess_zero/run.py", line 20, in <module>
    manager.start()
  File "src\chess_zero\manager.py", line 64, in start
    return self_play.start(config)
  File "src\chess_zero\worker\self_play.py", line 25, in start
    return SelfPlayWorker(config).start()
  File "src\chess_zero\worker\self_play.py", line 69, in start
    pretty_print(env, ("current_model", "current_model"))
  File "src\chess_zero\lib\data_helper.py", line 27, in pretty_print
    pyperclip.copy(env.board.fen())
  File "C:\Users\hanan\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 574, in lazy_load_stub_copy
    return copy(text)
  File "C:\Users\hanan\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 416, in copy_windows
    with clipboard(hwnd):
  File "C:\Users\hanan\Anaconda3\lib\contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "C:\Users\hanan\Anaconda3\lib\site-packages\pyperclip\__init__.py", line 400, in clipboard
    raise PyperclipWindowsException("Error calling OpenClipboard")
pyperclip.PyperclipWindowsException: Error calling OpenClipboard ([WinError 5] Access is denied.)
Exception in thread prediction_worker:
Traceback (most recent call last):
  File "C:\Users\hanan\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\hanan\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "src\chess_zero\agent\api_chess.py", line 62, in _predict_batch_worker
    while pipe.poll():
  File "C:\Users\hanan\Anaconda3\lib\multiprocessing\connection.py", line 257, in poll
    return self._poll(timeout)
  File "C:\Users\hanan\Anaconda3\lib\multiprocessing\connection.py", line 328, in _poll
    _winapi.PeekNamedPipe(self._handle)[0] != 0):
BrokenPipeError: [WinError 109] The pipe has been ended

The calling function and argument is:
pyperclip.copy('8/p7/3pk3/2p1b1Bp/4P2P/4NK2/2R5/4q3 b - - 10 52')

when I run the same command in a python shell it runs ok

as you can see from the remainder of the trace the program runs within the 'multiprocessing' framework, spawning several workers
could that be the problem causing the windows access problem?
do you have a suggestion how to fix it?

**Comment by taojy123** [comment]
I meet the same problem. 😂

**Comment by orrwil** [comment]
It appears that Windows clipboard is not available (at least to non admin user) when the computer is locked. There are workarounds on [Stackoverflow](https://stackoverflow.com/questions/34514644/in-python-3-how-can-i-tell-if-windows-is-locked/43758104).

**Comment by vietthong31** [comment]
Maybe because of BitLocker

**Comment by Aran-Fey** [comment]
What's the recommended way to catch this exception? I'm asking because I couldn't find `PyperclipWindowsException` mentioned anywhere in the docs. Is this part of the public API or not? Are there any other exceptions I should know of? Is there a base class for all pyperclip exceptions that I should catch instead?
