### ISSUE TITLE
Getting exception (pyperclip.PyperclipException) when copy text to clipboard

### ISSUE THREAD

**Issue by sashan4u007** [asweigart/pyperclip#170]
Getting exception (pyperclip.PyperclipException) when copy text to clipboard

**Python version :** 
```
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

```
**Linux version**
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
```

**Code**
```
>>> import pyperclip
>>> pyperclip.copy('The text to be copied to the clipboard.')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sashant@gmail.com/venv/rpa/lib/python3.6/site-packages/pyperclip/__init__.py", line 303, in __call__
    raise PyperclipException(EXCEPT_MSG)
pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error 
```

**Comment by sashan4u007** [comment]
Resolve above issue by running below command

`sudo apt-get install xclip`
