### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by azamet90** [asweigart/pyperclip#173]
```Traceback (most recent call last):
  File "azazazaz.py", line 369, in <module>
    main()
  File "azazazaz.py", line 282, in main
    menu()
  File "azazazaz.py", line 345, in menu
    Discord()
  File "azazazaz.py", line 95, in Discord
    if clipboard != pyperclip.paste():
  File "/home/atom/.local/lib/python3.8/site-packages/pyperclip/__init__.py", line 640, in lazy_load_stub_paste
    return paste()
  File "/home/atom/.local/lib/python3.8/site-packages/pyperclip/__init__.py", line 268, in paste_klipper
    assert len(clipboardContents) > 0
AssertionError```
this error gives on my friend pc but not on my!
the code im using is:
```python
def saveTheClipBoard():
    s = pyperclip.paste()
    with open('d-accounts.txt', 'w') as g:
        g.write(s)
        print("Email:", s)```
why this is happening on him but not on me?

**Comment by OKaluza** [comment]
I have this same or a similar issue, it is breaking dependant packages (running Kubuntu 21.04)

```
$ openstack --help
Service 'org.kde.klipper' does not exist.
Traceback (most recent call last):
  File "/home/owen/python-default/bin/openstack", line 5, in <module>
    from openstackclient.shell import main
  File "/home/owen/python-default/lib/python3.9/site-packages/openstackclient/shell.py", line 23, in <module>
    from osc_lib import shell
  File "/home/owen/python-default/lib/python3.9/site-packages/osc_lib/shell.py", line 24, in <module>
    from cliff import app
  File "/home/owen/python-default/lib/python3.9/site-packages/cliff/app.py", line 22, in <module>
    import cmd2
  File "/home/owen/python-default/lib/python3.9/site-packages/cmd2/__init__.py", line 30, in <module>
    from .cmd2 import Cmd
  File "/home/owen/python-default/lib/python3.9/site-packages/cmd2/cmd2.py", line 73, in <module>
    from .clipboard import (
  File "/home/owen/python-default/lib/python3.9/site-packages/cmd2/clipboard.py", line 14, in <module>
    _ = pyperclip.paste()
  File "/home/owen/python-default/lib/python3.9/site-packages/pyperclip/__init__.py", line 681, in lazy_load_stub_paste
    return paste()
  File "/home/owen/python-default/lib/python3.9/site-packages/pyperclip/__init__.py", line 301, in paste_klipper
    assert len(clipboardContents) > 0
AssertionError
```
I have worked around it by running klipper, which I don't normally use nor want to - not having klipper running should not prevent me from using openstack-client or any other package which uses this module.

This assertion seems unnecessary and pyperclip should be able to fail gracefully,
