### ISSUE TITLE
Conflict with Pyautogui, throwing Attribute Error

### ISSUE THREAD

**Issue by jmtakahashi** [asweigart/pyperclip#208]
Python Version: 3.9.6

I am using pyautogui and pyperclip in the same script.  When I import both modules, I get the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyperclip/__init__.py", line 659, in lazy_load_stub_copy
    return copy(text)
  File "/usr/local/lib/python3.9/site-packages/pyperclip/__init__.py", line 139, in copy_osx_pyobjc
    board.declareTypes_owner_([AppKit.NSStringPboardType], None)
  File "/usr/local/lib/python3.9/site-packages/objc/_lazyimport.py", line 207, in __getattr__
    raise AttributeError(name)
AttributeError: NSStringPboardType
`

But when I only use pyperclip, it works correctly.

The only documentation regarding the attribute error that I could find from apple was [this](https://developer.apple.com/documentation/appkit/nsstringpboardtype).

**Comment by Alexayzc** [comment]
Got the same issue today. Did u solve the problem in any way?
