### ISSUE TITLE
Requires a downgraded libffi

### ISSUE THREAD

**Issue by seagoj** [asweigart/pyperclip#218]
This originated with https://github.com/dbcli/mycli/issues/1008#issuecomment-973446530.

On arch linux the standard libffi package no longer includes libffi.so.7. Would it be possible to update pyperclip to use libffi.so.8?

```
Traceback (most recent call last):
  File "/home/seagoj/.local/bin/mycli", line 5, in <module>
    from mycli.main import cli
  File "/home/seagoj/.local/lib/python3.6/site-packages/mycli/main.py", line 40, in <module>
    from .packages.special.main import NO_QUERY
  File "/home/seagoj/.local/lib/python3.6/site-packages/mycli/packages/special/__init__.py", line 9, in <module>
    from . import dbcommands
  File "/home/seagoj/.local/lib/python3.6/site-packages/mycli/packages/special/dbcommands.py", line 5, in <module>
    from mycli.packages.special import iocommands
  File "/home/seagoj/.local/lib/python3.6/site-packages/mycli/packages/special/iocommands.py", line 11, in <module>
    import pyperclip
  File "/home/seagoj/.local/lib/python3.6/site-packages/pyperclip/__init__.py", line 52, in <module>
    import ctypes
  File "/home/seagoj/.asdf/installs/python/3.6.2/lib/python3.6/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by seagoj** [comment]
Nevermind. I think this was all due to an out of date python/pip. Nothing to see here...
