### ISSUE TITLE
KDE 5 Klipper broken

### ISSUE THREAD

**Issue by contrixed** [asweigart/pyperclip#26]
I will shortly attempt to see why this is occurring, but here is what happens if you try to use the latest release under KDE 5. (Please note this still works under KDE 4)

---------- Data ----------
```text
13:33 $ python -m unittest basicTests
Testing on: Python 2.7.9 - (KDE Klipper) - qdbus (external)                                                                                                       
Cannot find '.setClipboardContents' in object /klipper at org.kde.klipper                                                                                         
Service 'org.kde.klipper' does not exist.                                                                                                                         
FCannot find '.setClipboardContents' in object /klipper at org.kde.klipper                                                                                        
Service 'org.kde.klipper' does not exist.                                                                                                                         
F                                                                                                                                                                 
======================================================================
FAIL: test_copyPaste (basicTests.TestCopyPaste)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basicTests.py", line 15, in test_copyPaste
    self.assertEqual(pyperclip.paste(), msg)
AssertionError: u'' != 'The quick brown fox jumped over the yellow lazy dog.'

======================================================================
FAIL: test_randomCopyPaste (basicTests.TestCopyPaste)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "basicTests.py", line 24, in test_randomCopyPaste
    self.assertEqual(pyperclip.paste(), msg)
AssertionError: u'' != 'kioqdZBItNwtDuIYvfqjjoxIu8JWBUU1QCJgFPRYOWng5lVipdXSZ59s5K8cb04GWQyfTRltS3XhG3OGxDC40XnxhYLkDeH7AZ2Oy1CTo3F8NMjlKPQEAMzBe62607pcTwmEJ2s1UgaHzavNwshSVFfLkP4AKemr769rzbubncriqMaLmREdvVpyH9'

----------------------------------------------------------------------
Ran 2 tests in 0.072s

FAILED (failures=2)

**Comment by drakulavich** [comment]
Maybe [this](https://forum.kde.org/viewtopic.php?f=66&t=127184) thread on forum.kde.org  help.

**Comment by contrixed** [comment]
@drakulavich  So pretty much, they have completely disabled communication to Klipper via dbus? I've been reading those post and there is no explanation of how to now interact with Klipper. Perhaps for now, we will have to wait to see what KDE has planned of a new form of interaction for Klipper.

**Comment by drakulavich** [comment]
As I understood, klipper is [still available](https://www.kubuntuforums.net/showthread.php?68017-CLI-for-Plasma-5-Clipboard&p=371179&viewfull=1#post371179).

**Comment by contrixed** [comment]
Resolved; the method for Klipper 4 still works for Klipper 5.

**Comment by asweigart** [comment]
Is there something we can do about this though? We could at least check if the process object's returncode is not 0 (it is 1 if klipper is not running). Should we try to start klipper if it isn't running?

Otherwise, copy() and paste() don't raise any exceptions for the ``Cannot find '.setClipboardContents' in object /klipper at org.kde.klipper`` and ``Service 'org.kde.klipper' does not exist.`` error messages, but instead the program just keeps running.

**Comment by contrixed** [comment]
It seems for the dbus, you must start klipper like so in the terminal.
```bash
klipper
```
Then the dbus will function properly.

**Comment by drakulavich** [comment]
I think, pyperclip should not try and start klipper. It's a user's responsibility. I prefer returncode checking.
We can put RuntimeError exception in copy_klipper and paste_klipper if command fails.

**Comment by contrixed** [comment]
It would be best to auto-start the process. i see nothing wrong with PyPerclip doing so, However just to note that method would only be needed for KDE 5.

**Comment by ilpianista** [comment]
IMHO we should check if klipper is running instead of just checking [that's installed](https://github.com/asweigart/pyperclip/blob/master/pyperclip/__init__.py#L80).

**Comment by mkrutov** [comment]
I would expect that checking if service is ran to be the valid behaviour instead of checking if its installed. still not the case, coallegue has hit it in #202.
