### ISSUE TITLE
pip install fails on Cygwin

### ISSUE THREAD

**Issue by samisalkosuo** [asweigart/pyperclip#55]
When using pip install pyperclip on latest Cygwin (Windows 10) using Python 3.4.3 installation fails:

```
Collecting pyperclip
  Using cached pyperclip-1.5.25.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-323sgh0o/pyperclip/setup.py", line 8, in <module>
        version=__import__('pyperclip').__version__,
      File "/tmp/pip-build-323sgh0o/pyperclip/pyperclip/__init__.py", line 99, in <module>
        copy, paste = determine_clipboard()
      File "/tmp/pip-build-323sgh0o/pyperclip/pyperclip/__init__.py", line 53, in determine_clipboard
        return init_windows_clipboard(cygwin=True)
      File "/tmp/pip-build-323sgh0o/pyperclip/pyperclip/windows.py", line 26, in init_windows_clipboard
        from ctypes.wintypes import (HGLOBAL, LPVOID, DWORD, LPCSTR, INT, HWND,
      File "/usr/lib/python3.4/ctypes/wintypes.py", line 20, in <module>
        class VARIANT_BOOL(ctypes._SimpleCData):
    ValueError: _type_ 'v' not supported

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-323sgh0o/pyperclip
```

**Comment by tkossak** [comment]
I have the same problem.
Windows 7 x64
Cygwin x64
Python 3.4
pip 7.1.2

**Comment by liuyug** [comment]
I catch the same problem
Windows 7 x64
Cygwin x64
python 2.7
pip 7.1.2

**Comment by drakulavich** [comment]
The same problem with ctypes.wintypes import...

Maybe we should implement cygwin copy/paste functions using `/dev/clipboard`. Guys, what do you think?

**Comment by asweigart** [comment]
With the recent merges, cygwin support now mostly works so I'm closing this issue.

**Comment by ahernsean** [comment]
Any way to suppress the warning message? Things are working well for me on Cygwin.
