### ISSUE TITLE
OSError on Win10 Py 3.5

### ISSUE THREAD

**Issue by asweigart** [asweigart/pyperclip#65]
A user reported this exception on Windows 10, Python 3.5:

========= RESTART: C:\Users\Russ\Desktop\python_work
Traceback (most recent call last):
  File "C:\Users\Russ\Desktop\python_work\pyperclip.py", line 70, in winSetClipboard
    ctypes.cdll.msvcrt.strcpy(ctypes.c_char_p(pchData), bytes(text))
TypeError: string argument without an encoding

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Russ\Desktop\python_work\ceasarCipher.py", line 52, in <module>
    pyperclip.copy(translated)
  File "C:\Users\Russ\Desktop\python_work\pyperclip.py", line 73, in winSetClipboard
    ctypes.cdll.msvcrt.strcpy(ctypes.c_char_p(pchData), bytes(text, 'ascii'))
OSError: exception: access violation writing 0x0000000000000000

**Comment by mhils** [comment]
Ok, but we currently neither have a file called `pyperclip.py` nor a call to `msvcrt.strcpy` in the codebase?

**Comment by hugovk** [comment]
I suggest this is closed, unless more information can be provided.
